name: E2E Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop

jobs:
  build-push-run-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v4


      - name: Build and push Docker image to GCP artifact registry
        run: |
          echo "Building Docker image"
          echo "VERSION=develop"
          echo "COMMIT_SHA=${{ github.sha }}"

      - name: Create training workload
        id: create_workload
        run: |
          echo "Running tests"
