name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run pre-commit
        run: echo "running pre-commit"
